#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  for nm_service in "$@"; do
    case "$nm_service" in
      default)
        shift
        exec caddy "$@"
        ;;
    esac
  done
}

main "$@"

